### ISSUE TITLE
Fix vulnerable npm packages

### ISSUE THREAD

**Issue by hazuremon** [UBCCM/ubc-clf8#31]
**Please perform a [cursory search](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Aubccm%2Fubc-def) before reporting an issue.**

**Describe the bug in detail**  
The current gulp task runner has lots of vulnerable dependencies, as reported in Snyk and Github security. Some of these dependencies are not recommended anymore as they haven't been updated by the maintainer for over a year.
Vulnerable packages:
1. gulp-autoprefixer
2. gulp-cssnano

**To Reproduce**  
Run "npm audit" to get currently list of vulnerable packages reported by Snyk.

**Expected behavior**  
Update and replace vulnerable packages
1. Replace gulp-autoprefixer with PostCSS and autoprefixer packages. The recommended approach to autoprefixer.
2. Use of autoprefixer's .browserlistrc config file
3. Replace gulp-cssnano with PostCSS and cssnano packages. The recommended setup for cssnano.
4. Update other out of date packages as needed.

**Comment by occupant** [comment]
I have a branch that addresses some of these issues. Essentially, it migrates from gulp to npm scripts. https://github.com/occupant/ubc-clf8/tree/remove-gulp 

Other changes in that branch:

- removed SCSS as a dependency so I could evaluate a fully postcss workflow.
- removed sasslint and replaced with stylelint (much more active project, not limited to SCSS, can also parse css in js, SCSS, LESS, html, pug, etc.). I definitely would recommend this regardless of any other changes.
- added twig support (twig may only be useful to a limited number of users - but the ability to template html is something we should consider in my opinion).
- added browserlist definition to package.json
- added liveserver with live style injection
- make use of node environment [NODE ENV] variables

We can discuss if you think it may be valuable.

**Comment by hazuremon** [comment]
We should discuss and review, as there are quite a lot of changes that you are trying to implement in your branch.

For this issue, I just keep it to fixing the two outdated and high vulnerable packages that are currently in our package.

**Comment by richardtape** [comment]
Thanks for doing this, @hazuremon.

I like the idea of `stylelint` and prefer active packages that are more generic, especially as it can handle css-in-js which is a pattern that a lot of people are now adopting (I'm not a fan, but whatever)

A live server is a good idea, but I'm worried that this may interfere with other people's workflows. It's probably a lack of knowledge on my part, but happy to have a chat.

Node Environment variables are good in my book.

Twig support I'm very much on the fence about. Does having twig support change, in any noticeable way, the file size of our output? Is it possible to run in a "I don't care for Twig at all" mode?

**Comment by occupant** [comment]
@hazuremon , I agree, keep the issue focussed on the task at hand. If the decision is to stay with gulp (which requires these intermediate packages), then update / replace any packages as needed.

@richardtape RE: twig - I don't think we should add this per se, but I think an html templating language like it is worth considering. 

The branch I linked to was really for me to explore and figure out what would work best for me. I know there are certainly things in there that won't be of general use. Think of it more as a discussion point :)

**Comment by hazuremon** [comment]
@occupant I do think we should move away from gulp, but I would keep it out of this issue and pull request, and suggest to create a separate "feature request" issue to have that conversation.
