### ISSUE TITLE
Include CSS linter

### ISSUE THREAD

**Issue by occupant** [UBCCM/ubc-clf8#44]
**Problem** 
As part of a modern shared web dev toolchain, a linter is a critical tool for maintaining CSS consistency and cleanliness. It can help identify and prevent common issues from moving into production code, as well as make the code more readable.

**Proposed solution**  
There are number of packages we could consider. The most commonly used are listed on [npm trends](https://www.npmtrends.com/sass-lint-vs-stylelint-vs-csscomb-vs-csslint-vs-css-lint-vs-clean-css).

I suggest using [stylelint](https://stylelint.io) for now, as it is very well maintained, has a well-established community with pre-built configurations that can be extended as needed. Additionally, unlike a tool like sass-lint that simply reports errors, there is a flag that can automatically fix most errors. This can be done within many filetypes (sass, less, css, js, etc), although some require postcss.

[A sample config file](https://github.com/occupant/ubc-clf8/blob/postcss/.stylelintrc.json).

**Alternatives Considered**  
Previously we considered [sass-lint](https://github.com/sasstools/sass-lint), however this package is currently unmaintained.

[clean-css](https://github.com/jakubpawlowicz/clean-css) currently has more downloads and looks to be very well used, however I'm admittedly not as familiar with it. It looks to be very flexible, however I haven't come across something similar to the [shared configurations](https://stylelint.io/#extend-a-shared-configuration) (meaning we manage more). Totally open to discussing this though.

**Comment by hazuremon** [comment]
Definitely, we need this as part of the CI. I would suggest tying this to the code review process as part of the automated QA process.

For rules in the sample config file, is this your proposed config or just as a sample?

**Comment by occupant** [comment]
The sample config is what I've been using and I think it's a good place to start. It first includes [stylelint-config-standard](https://github.com/stylelint/stylelint-config-standard) (a boilerplate for common stylistic standards) and [stylelint-config-rational-order](https://github.com/constverum/stylelint-config-rational-order) (which corresponds pretty well to the sort ordering we have discussed and agreed upon previously).

Then there are a few rules for our specific config. Assuming we use tailwind, I've ok'd the @responsive rule with
```
at-rule-no-unknown": [true, {
			"ignoreAtRules": ["responsive"]
		}],
```
etc.

We can go through them one by one if needed and adjust where necessary.
