### ISSUE TITLE
Add Contribution Rules

### ISSUE THREAD

**Issue by occupant** [UBCCM/ubc-clf8#8]
As a sample:
https://github.com/occupant/sass-lint/blob/develop/CONTRIBUTING.md

This is much more restrictive than we need to be, but has some interesting ideas, esp. the Developer Certificate of Origin. Basically it's asking you to go through self-verification.

The git message guideline are also nice - recommended tense (present, declarative I think?).

**Comment by hazuremon** [comment]
Working towards finalizing a contributing.md in one of the branch. Will link the pull request to this issue once the guideline is ready to be add to core.

**Comment by hazuremon** [comment]
Marking this as duplicate to #29 as this falls into larger pull request approval process
